### ISSUE TITLE
Types doesn't seem to be exported properly for hoofd/preact

### ISSUE THREAD

**Issue by Bowser65** [JoviDeCroock/hoofd#28]
I've been experiencing some issues with TypeScript yelling at me because it couldn't find the typings for this module. Knowing it is written in TypeScript and having used it in a React project, I knew for sure typings do exists so I started digging to figure out what was going wrong.

It seems microbundle always outputs the typings in `/dist` when bundling for Preact, while the `package.json` in the `preact` folder seems to expect them to be present in `/preact/dist`, hence why TypeScript doesn't seem able to locate the typings.

Changing the `types` and `typings` properties in `preact/package.json` to point the parent `dist` folder (`../dist/index.d.ts`) seemed to work good enough, but I don't know if it's a viable solution for you. If it's fine, I can shoot a PR to address this issue.

**Comment by JoviDeCroock** [comment]
Fixed in https://github.com/JoviDeCroock/hoofd/commit/236cc69ba8bedd59aaf2eaea3875a99c87a602e2 will release a patch later today, thanks for bringing this up!
