### ISSUE TITLE
scripts

### ISSUE THREAD

**Issue by wmertens** [JoviDeCroock/hoofd#30]
I'm currently using Helmet but I do prefer the hooks approach you offer.

One thing I'm missing is `<script>` support. It's nice to be able to encapsulate trackers and other scripts that have to go in `<head>` for technical reasons so they can be placed where they make sense in the application.

Helmet's support for `<script>` is very rudimentary IMHO - it just adds the tag without regards for SSR-rendered previous tags, and if you put in an inline script, it won't run it, so that will only work for SSR.

So, ideally, hoofd would:
* support script tags
* mark SSR-ed script tags in a way they can be recognized after hydration
* only add script tags once, also after hydration
* `eval` inline scripts when run in the browser, but add them to `<head>` when run during SSR

But, I would already be happy with simply supporting the tag.

**Comment by JoviDeCroock** [comment]
Hey,

> eval inline scripts when run in the browser, but add them to <head> when run during SSR

Honestly, I don't really feel comfortable allowing arbitrary evaluation or injection of scripts 

The other things should be possible

**Comment by wmertens** [comment]
The problem is that most trackers require an inline script as well as a regular script. So this solution would not be enough.
Furthermore, you are already allowing arbitrary evaluation of scripts, only they are in the form of hosted scripts instead of inline scripts...

Also, since you're adding the script elements via DOM manipulation, I believe there's no need to eval, the browser will honor the script tag anyway?

Other than that, the PR looks great!

**Comment by ggoodman** [comment]
I wonder if the inline use-case could be adequately addressed using data-uris, like:

```js
useScript({ src: 'data:application/javascript,alert("yolo")' });
```

![image](https://user-images.githubusercontent.com/50030/112561797-4a937080-8dac-11eb-8194-d85715cee6ec.png)

**Comment by wmertens** [comment]
Great idea!

**Comment by JoviDeCroock** [comment]
Closing and pushing #35 and #31 in a 1.2.0 release

**Comment by ggoodman** [comment]
@JoviDeCroock, should `type` be marked as optional in `ScriptOptions`?

**Comment by JoviDeCroock** [comment]
Ah damn, forgot about that 😅
